// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJVKS4-WddDrg_xJaejSCw5J36fR7A_E',
    appId: '1:235047510456:web:0044fff7abc51782f0af4d',
    messagingSenderId: '235047510456',
    projectId: 'quan-ly-chi-tieu-34e67',
    authDomain: 'quan-ly-chi-tieu-34e67.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-34e67.firebasestorage.app',
    measurementId: 'G-H843VSTCV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPPBJMeMu8-eaCXGcc229Quv4Jz1PUM6w',
    appId: '1:235047510456:android:d44f1918e5e0544ef0af4d',
    messagingSenderId: '235047510456',
    projectId: 'quan-ly-chi-tieu-34e67',
    storageBucket: 'quan-ly-chi-tieu-34e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcla4enqRTyse4n7pEUDS7XE-dF57DtTo',
    appId: '1:235047510456:ios:6f26cf83aa61df46f0af4d',
    messagingSenderId: '235047510456',
    projectId: 'quan-ly-chi-tieu-34e67',
    storageBucket: 'quan-ly-chi-tieu-34e67.firebasestorage.app',
    iosBundleId: 'com.example.flutterMoneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcla4enqRTyse4n7pEUDS7XE-dF57DtTo',
    appId: '1:235047510456:ios:6f26cf83aa61df46f0af4d',
    messagingSenderId: '235047510456',
    projectId: 'quan-ly-chi-tieu-34e67',
    storageBucket: 'quan-ly-chi-tieu-34e67.firebasestorage.app',
    iosBundleId: 'com.example.flutterMoneyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbJVKS4-WddDrg_xJaejSCw5J36fR7A_E',
    appId: '1:235047510456:web:cb5ea0a17f681825f0af4d',
    messagingSenderId: '235047510456',
    projectId: 'quan-ly-chi-tieu-34e67',
    authDomain: 'quan-ly-chi-tieu-34e67.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-34e67.firebasestorage.app',
    measurementId: 'G-8GX48LF7LP',
  );
}
